parameters:
  projectName: '' # Overridden in each pipeline file

jobs:
- job: Build_${{ parameters.projectName }}
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    projectPath: 'src/${{ parameters.projectName }}/${{ parameters.projectName }}.csproj'
  steps:
  - script: |
      set -e
      set -x
      dotnet restore $(projectPath)
      dotnet build $(projectPath) --configuration $(BuildConfiguration)
      dotnet pack $(projectPath) --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: ${{ parameters.projectName }}
      pathtoPublish: $(Build.ArtifactStagingDirectory)
