name: $(majorVersion).$(minorVersion)$(Rev:.r)

# define two variables 'dockerId' and 'dockerPassword' in the build pipeline in UI for your ACR credentials
trigger:
  branches:
    include:
    - dev

variables:
- name: majorVersion
  value: 0
- name: minorVersion
  value: 0
- name: BuildConfiguration
  value: Release

jobs:
- template: azure-pipelines.template.yml
  parameters:
    projectName: 'AspNet.Security.OAuth.Discord'
- template: azure-pipelines.template.yml
  parameters:
    projectName: 'AspNet.Security.OAuth.Spotify'
- template: azure-pipelines.template.yml
  parameters:
    projectName: 'AspNet.Security.OAuth.Twitch'
