parameters:
  buildName: '' # Overridden in each pipeline file
  projectName: '' # Overridden in each pipeline file

jobs:
- job: Build_${{ parameters.buildName }}
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    projectPath: 'src/${{ parameters.projectName }}/${{ parameters.projectName }}.csproj'
  steps:
  - task: DotNetCoreInstaller@0
      displayName: 'Use .NET Core sdk 3.0.100-preview3'
      inputs:
        version: 3.0.100-preview3
  - script: |
      set -e
      set -x
      dotnet restore $(projectPath)
      dotnet build $(projectPath) --configuration $(BuildConfiguration)
      dotnet pack $(projectPath) --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: ${{ parameters.projectName }}
      pathtoPublish: $(Build.ArtifactStagingDirectory)

